### ISSUE TITLE
Bug: caution is not capitalized in Github theme

### ISSUE THREAD

**Issue by PipeItToDevNull** [lin-stephanie/rehype-callouts#15]
### Bug description

Hi, it seems that https://github.com/lin-stephanie/rehype-callouts/blob/af0a2ba287cd9b95de456806c447a397ba60c3bb/src/themes/github/config.ts#L29 is lowercase when it should be capital.

Thanks!

### Steps to reproduce

Use the application

**Comment by lin-stephanie** [comment]
Thanks for spotting the issue! It’s fixed now. Appreciate it!
