### ISSUE TITLE
Feature: Use blockquote instead of div or make confugurable

### ISSUE THREAD

**Issue by TotallyInformation** [lin-stephanie/rehype-callouts#8]
### Goal or desired outcome

This plugin currently does not really produce semantic markup it seems. The desirable outcome would be to either output a top-level blockquote instead of a div or, possibly even better, have the top-level tag as a configurable setting.

### Feature description

Either swap the outer `div` tag for a `blockquote` tag or allow the outer tag to be configurable.

**Comment by lin-stephanie** [comment]
@TotallyInformation Thanks for the feature request—it highlighted the semantic markup issue for me. I've now added an `htmlTagNames` option in https://github.com/lin-stephanie/rehype-callouts/commit/0c789f4ec500a1199c0ca8099831be8f60ebed70 to allow more flexible HTML tag naming. 

For collapsible callouts, though, the `details` and `summary` tags are functionally required, but I think using `collapsibleContentTagName` could achieve a similar semantic effect. What do you think of this approach?

**Comment by lin-stephanie** [comment]
Thanks for sharing your thoughts! I totally agree on balancing semantics with practical functionality. The plugin will keep using details and summary as a no-JS option for those who prefer it. Additionally, I'm planning to add aria attributes to improve accessibility.

Great to discuss these ideas with you!

**Comment by lin-stephanie** [comment]
Thanks for sharing your thoughts. I totally agree that your approach is a great way to balance semantics with practical functionality. 

The plugin will keep using `details` as a no-JS option for those who prefer it, and I’m planning to add aria attributes to improve accessibility.

Great to discuss these ideas with you!

**Comment by TotallyInformation** [comment]
Nice, thanks for your responsiveness. 😊 Will keep a watch on the repo. Will close this now. Thanks again.
